<?php

namespace Zoo\AnimalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CageRepository extends EntityRepository
{
}
